apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '8m'
    nginx.ingress.kubernetes.io/client-max-body-size: '8m'
    nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: '256m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
spec:
  rules:
    - host: www.photo-share.us
      http:
        paths:
          - pathType: Prefix
            path: /api/followers/?(.*)
            backend:
              service:
                name: followers-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/posts/?(.*)
            backend:
              service:
                name: posts-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/messages/?(.*)
            backend:
              service:
                name: messages-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/notifications/?(.*)
            backend:
              service:
                name: followers-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/reactions/?(.*)
            backend:
              service:
                name: posts-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/users/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
    - host: photo-share.us
      http:
        paths:
          - pathType: Prefix
            path: /api/followers/?(.*)
            backend:
              service:
                name: followers-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/posts/?(.*)
            backend:
              service:
                name: posts-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/messages/?(.*)
            backend:
              service:
                name: messages-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/notifications/?(.*)
            backend:
              service:
                name: followers-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/reactions/?(.*)
            backend:
              service:
                name: posts-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/users/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
    service.beta.kubernetes.io/do-loadbalancer-protocol: 'http'
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
    service.beta.kubernetes.io/do-loadbalancer-algorithm: 'round_robin'
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: '443'
    service.beta.kubernetes.io/do-loadbalancer-hostname: 'photo-share.us'
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: '67c0e75e-9d68-4014-bf5e-0976a57077a9'
  labels:
    helm.sh/chart: ingress-nginx-2.0.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
