apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ggabella91/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mailtrap-user
                  key: EMAIL_USERNAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailtrap-pass
                  key: EMAIL_PASSWORD
            - name: EMAIL_HOST
              value: 'smtp.mailtrap.io'
            - name: EMAIL_PORT
              value: 2525
            - name: EMAIL_FROM
              value: 'giuliano@photo-share.dev'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
