apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-photo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-photo
  template:
    metadata:
      labels:
        app: auth-photo
    spec:
      containers:
        - name: auth-photo
          image: ggabella91/auth-photo
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-photo-mongo-srv:27017/auth-photo'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-photo-srv
spec:
  selector:
    app: auth-photo
  ports:
    - name: auth-photo
      protocol: TCP
      port: 3000
      targetPort: 3000
