apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followers
  template:
    metadata:
      labels:
        app: followers
    spec:
      containers:
        - name: followers
          image: ggabella91/followers
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: photo-share
            - name: MONGO_URI
              value: 'mongodb://followers-mongo-srv:27017/followers'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: followers-srv
spec:
  selector:
    app: followers
  ports:
    - name: followers
      protocol: TCP
      port: 3000
      targetPort: 3000
