apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: ggabella91/posts
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: photo-share
            - name: MONGO_URI
              value: 'mongodb://posts-mongo-srv:27017/posts'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: REDIS_HOST
              value: posts-redis-srv
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
            - name: REDIS_CACHE_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: redis-cache-exp
                  key: REDIS_CACHE_EXPIRATION
            - name: POSITION_STACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: position-stack-api-key
                  key: POSITION_STACK_API_KEY
            - name: MAPBOX_GL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mapbox-gl-access-token
                  key: MAPBOX_GL_ACCESS_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 3000
      targetPort: 3000
