name: tests-email

on:
  pull_request:
    paths:
      - 'email/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd email && npm install && npm run test:ci
